INSERT INTO KR_EMPLOYEE (EMP_ID,EMP_NAME,EMP_ROLE,EMP_COMPANY,EMP_SALARY)
VALUES (1,'Kranthi','SSE','Infosys',34500.78);

INSERT INTO KR_EMPLOYEE (EMP_ID,EMP_NAME,EMP_ROLE,EMP_COMPANY,EMP_SALARY)
VALUES (2,'Kumar','TA','Infy',35000.98);