CREATE TABLE KR_EMPLOYEE (
         EMP_ID      NUMBER PRIMARY KEY,
         EMP_NAME      VARCHAR2(100) NOT NULL,
         EMP_ROLE      VARCHAR2(100),
         EMP_COMPANY   VARCHAR2(100),
         EMP_SALARY  NUMBER NOT NULL);